[modules.Cuckoo]
imports = ["Foundation"]
testableImports = ["Cuckoo"]
sources = [
    "./CuckooP2/CommentList/Service/*.swift",
]
exclude = [
    "ExcludedTestClass",
    "ExcludedProtocol",
]
# regex = ""
output = "./CuckooP2Tests/GeneratedMocks/Mocks.swift"


[modules.Cuckoo.options]
glob = true
keepDocumentation = false

[modules.Cuckoo.xcworkspace]
path = "Generator"
target = "Cuckoonator"
