output = "./CuckooP2Tests/GeneratedMocks/Mocks.swift"

[modules.CuckooP2.xcworkspace]
testable = true
files = [
  "./CuckooP2/CommentList/Service/CommentViewService.swift",
  # Add other files if needed
]
