# You can define a fallback output for all modules that don't define their own.
output = "CuckooP2Tests/GeneratedMocks/GeneratedMocks.swift"

[modules.CuckooP2]
output = "CuckooP2Tests/GeneratedMocks/GeneratedMocks.swift"
# Standard imports added to the generated file(s).
imports = ["Foundation"]
# @testable imports if needed.
testableImports = ["CuckooP2"]
sources = [
    "CuckooP2/CuckooP2/CommentList/Service/*.swift",
]
exclude = ["ExcludedTestClass"]
# Optionally you can use a regular expression to filter only specific classes/protocols.
# regex = ""

[modules.CuckooP2.options]
# glob = false
# Docstrings are preserved by default, comments are omitted.
keepDocumentation = false
# enableInheritance = false
# protocolsOnly = true
# omitHeaders = true

# If specified, Cuckoo can also get sources for the module from an Xcode target.
[modules.CuckooP2.xcodeproj]
# Path to folder with .xcodeproj, omit this if it's at the same level as Cuckoofile.
path = ""
target = "CuckooP2"


